apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless
resources:
  - persistent-volume-redis.yaml
  - redis-helmrepo.yaml
  - redis-pass-secret.yaml
  - redis-helmrelease.yaml
  - redis-grafana-dashboard.yaml
