apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
spec:
  interval: 1h
  chart:
    spec:
      chart: redis
      version: ">=7.0.0"
      sourceRef:
        kind: HelmRepository
        name: redis
  valuesFrom:
    - kind: Secret
      name: redis-pass
      valuesKey: pass
      targetPath: "auth.password"
  values:
    architecture: standalone
    auth:
      enabled: true
      sentinel: true
      usePasswordFiles: false
    metrics:
      enabled: true
      service:
        enabled: true
      serviceMonitor:
        enabled: true
    master:
      persistence:
        existingClaim: redis
