apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: ${db_name}
spec:
  mariaDbRef:
    name: mariadb
    namespace: db
  characterSet: utf8
  collate: utf8_general_ci
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: ${db_name}
spec:
  maxUserConnections: ${db_max_connections}
  mariaDbRef:
    name: mariadb
    namespace: db
  passwordSecretKeyRef:
    name: ${db_userpass_secret}
    key: pass
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: ${db_name}-grant
spec:
  mariaDbRef:
    name: mariadb
    namespace: db
  privileges:
    - "ALL"
  database: "${db_name}"
  table: "*"
  username: ${db_name}
  grantOption: false
