---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 24h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-secgroup-oidc
  namespace: kube-system
data:
  values.yaml: |
    controller:
      service:
        annotations:
          oci-network-load-balancer.oraclecloud.com/oci-network-security-groups: "ocid1.networksecuritygroup.oc1.eu-frankfurt-1.aaaaaaaakcqf3xeu3cv72z7catcuoyc5f5j6c3jh2yl33w22oq4tbbwjuyya"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-secgroup-oidc
  namespace: kube-system
data:
  values.yaml: |
    controller:
      service:
        annotations:
          oci-network-load-balancer.oraclecloud.com/oci-network-security-groups: "ocid1.networksecuritygroup.oc1.eu-frankfurt-1.aaaaaaaa4rqdgtxhdms6c2xcijchw7y3tthfpqklvqytnzcrpv2qynv3zqsq"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: ingress-secgroup-oidc
  values:
    metrics:
      enabled: true
    # based on https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml
    controller:
      ingressClassResource:
        enabled: true
        name: nginx
        default: true
      minAvailable: 1
      replicaCount: 2
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
        prometheusRule:
          enabled: true
          rules:
            - alert: NGINXConfigFailed
              expr: count(nginx_ingress_controller_config_last_reload_successful == 0) > 0
              for: 1s
              labels:
                severity: critical
              annotations:
                description: bad ingress config - nginx config test failed
                summary: uninstall the latest ingress changes to allow config reloads to resume
            - alert: NGINXTooMany500s
              expr: 100 * ( sum( nginx_ingress_controller_requests{status=~"5.+"} ) / sum(nginx_ingress_controller_requests) ) > 5
              for: 1m
              labels:
                severity: warning
              annotations:
                description: Too many 5XXs
                summary: More than 5% of all requests returned 5XX, this requires your attention
            - alert: NGINXTooMany400s
              expr: 100 * ( sum( nginx_ingress_controller_requests{status=~"4.+"} ) / sum(nginx_ingress_controller_requests) ) > 5
              for: 1m
              labels:
                severity: warning
              annotations:
                description: Too many 4XXs
                summary: More than 5% of all requests returned 4XX, this requires your attention
      service:
        type: LoadBalancer
        enableHttp: true
        enableHttps: true
        nodePorts:
          http: 32322
          https: 32757
        annotations:
          # based on: https://github.com/oracle/oci-cloud-controller-manager/blob/master/docs/load-balancer-annotations.md
          oci.oraclecloud.com/load-balancer-type: "nlb"
          oci-network-load-balancer.oraclecloud.com/security-list-management-mode: "None"
