apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless
resources:
  - namespace.yaml
  - paperless-helmrepo.yaml
  - ../../mariadb-database-and-user/db.yaml
  - db-paperless-secret.yaml
  - paperless-secret-admin-pass.yaml
  - paperless-secret-key.yaml
  - persistent-volume-paperless.yaml
  - paperless-helmrelease.yaml
  - paperless-extra-deployments.yaml
  - ./redis
