apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 1h
  path: ./infra/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      grafana_domain: grafana.krbec.dev
      grafana_url: https://grafana.krbec.dev/grafana
